### ISSUE TITLE
Modules per project

### ISSUE THREAD

**Issue by jamlen** [jamlen/de-cli#1]
Modules are currently only supported at the top level, and all projects are scanned when `npm link`ing. This would be better if a project can list its modules.

Example config:

```yaml
---
folder: ~/dev/src
defaultRepo: git@github.com
projects:
  - name: project1
    description: Node.JS project 1
    defaultBranch: develop
    repos:
      - jamlen/de-sample-api
      - jamlen/de-sample-ui
    modules:
      - jamlen/de-utils

modules:
  - guzzlerio/deride@develop
```
